
import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // Navigation and layout
    dashboard: 'Dashboard',
    components: 'Components',
    dinosaurs: 'Dinosaurs',
    devices: 'Devices',
    sales: 'Sales',
    search: 'Search',
    bom_management: 'BOM Management',
    inventory_management: 'Inventory Mngmt.',
    odoo_sync: 'Odoo Sync',
    versions: 'Versions',
    quality_control: 'Quality Control',
    db_admin: 'DB Admin',
    management: 'Management',
    quick_stats: 'Quick Stats',
    inventory_manager: 'Inventory Manager',
    
    // Dashboard
    dashboard_title: 'DinoTrack Dashboard',
    dashboard_subtitle: 'Your dinosaur inventory control panel',
    total_components: 'Total Components',
    total_dinosaurs: 'Total Dinosaurs',
    total_sales: 'Total Sales',
    available_dinos: 'Available Dinos',
    low_stock: 'Low Stock',
    sales_this_week: 'Sales This Week',
    recent_dinosaurs: 'Recent Dinosaurs',
    critical_components: 'Critical Components',
    all_components_sufficient_stock: 'All components have sufficient stock',
    no_dinosaurs_registered: 'No dinosaurs registered',
    
    // Components page
    component_management: 'Component Management',
    manage_parts_components_inventory: 'Manage your parts and components inventory',
    add_component: 'Add Component',
    search_components_placeholder: 'Search components by name, batch, or serial...',
    category: 'Category',
    tracking: 'Tracking',
    all: 'All',
    by_batch: 'By Batch',
    by_unit: 'By Unit',
    chips: 'Chips',
    batteries: 'Batteries',
    sensors: 'Sensors',
    motors: 'Motors',
    structures: 'Structures',
    others: 'Others',
    no_components_registered: 'No components registered',
    start_adding_first_component: 'Start by adding your first component to the inventory',
    confirm_delete_component: 'Are you sure you want to delete component "{componentName}"? This action cannot be undone.',
    
    // Dinosaurs page
    dinosaur_registration_station: 'Dinosaur Registration Station',
    register_dinosaurs_step_by_step: 'Register dinosaurs with step-by-step guided assistant.',
    assembly_station: 'Assembly Station',
    registration_assistant: 'Registration Assistant',
    select_dinosaur_version_step: '1. Select Dinosaur Version',
    select_color_step: '2. Select Color',
    scan_plush_rfid_step: '3. Scan Plush RFID',
    scan_device_id_step: '4. Scan Device ID',
    additional_notes_step: '5. Additional Notes (Optional)',
    confirm_register_step: '6. Confirm and Register',
    choose_version: 'Choose version...',
    select_color: 'Select color...',
    waiting_rfid_scan: 'Waiting for RFID scan...',
    device_id_placeholder: 'Device ID...',
    special_observations_placeholder: 'Special observations, modifications, etc...',
    continue: 'Continue',
    back: 'Back',
    register_dinosaur: 'Register Dinosaur',
    version: 'Version',
    color: 'Color',
    device_id: 'Device ID',
    step_x_of_y: 'Step {current} of {total}',
    search_rfid_device_placeholder: 'Search by RFID or device ID...',
    total_dinosaurs: 'Total: {count} dinosaurs',
    all_statuses: 'All Statuses',
    all_colors: 'All Colors',
    all_versions: 'All Versions',
    available: 'Available',
    sold: 'Sold',
    maintenance: 'Maintenance',
    damaged: 'Damaged',
    unverified: 'Unverified',
    pink: 'Pink',
    teal: 'Teal',
    lavender: 'Lavender',
    green: 'Green',
    interference_detected_rfids: 'Interference detected! Multiple RFID tags are too close. Please separate them and scan again.',
    missing_data_restart_process: 'Missing required data. Please restart the registration process.',
    device_not_found_warning: 'Device with ID "{deviceId}" not found in ready status. Do you want to register anyway?',
    error_registering_dinosaur: 'Error registering dinosaur. Please try again.',
    force_register_warning_note: 'WARNING: Forced registration. Device {deviceId} was not found in ready status.',
    error_force_register: 'Error during force registration. Please try again.',
    cannot_delete_sold_dinosaur: 'Cannot delete a dinosaur that has already been sold.',
    confirm_delete_dinosaur: 'Are you sure you want to delete dinosaur with RFID {rfid_code}? This action cannot be undone.',
    dinosaur_registered_successfully_rfid: 'Dinosaur registered successfully! RFID:',
    device: 'Device',
    assembled_by: 'Assembled By',
    device_defective_warning: 'Device {deviceId} is marked as defective. Do you want to register anyway?',
    qc_failed_warning: 'Device {deviceId} failed QC tests: {failedTests}. Do you want to register anyway?',
    qc_not_tested_warning: 'Device {deviceId} has not been tested in QC. Do you want to register anyway?',
    device_not_ready_warning: 'Device {deviceId} is in "{status}" status, not ready. Do you want to register anyway?',
    force_register_note_defective: 'WARNING: Forced registration. Device {deviceId} is marked as defective.',
    force_register_note_qc_failed: 'WARNING: Forced registration. Device {deviceId} failed QC tests: {failedTests}.',
    force_register_note_qc_not_tested: 'WARNING: Forced registration. Device {deviceId} has not been tested in QC.',
    force_register_note_not_ready: 'WARNING: Forced registration. Device {deviceId} is in non-ready status.',
    force_register_note_device_not_found: 'WARNING: Forced registration. Device {deviceId} was not found in inventory.',
    continue_anyway: 'Continue Anyway',
    cancel_and_review: 'Cancel and Review',
    
    // Dinosaur Versions page
    dinosaur_versions: 'Dinosaur Versions',
    create_manage_configurations: 'Create and manage dinosaur configurations and recipes',
    create_version: 'Create Version',
    edit_version: 'Edit Version',
    create_new_version: 'Create New Version',
    model_name: 'Model Name',
    available_colors: 'Available Colors',
    write_color_placeholder: 'Write color (e.g., pink)',
    components_configuration: 'Components Configuration',
    option_1_scan_batch: 'Option 1: Scan the barcode of a batch or serial number of the component to add it.',
    scan_batch_serial_placeholder: 'Scan batch or serial number...',
    option_2_select_manually: 'Option 2: Select a component manually.',
    select_component: 'Select component',
    select_batch: 'Select batch',
    add: 'Add',
    added_components: 'Added Components ({count})',
    batch: 'Batch',
    individual: 'Individual',
    version_notes: 'Version Notes',
    version_notes_placeholder: 'Special features, assembly notes, version changes, etc...',
    cancel: 'Cancel',
    saving: 'Saving...',
    saved: 'Saved',
    save_error: 'Error saving',
    no_versions_created: 'No versions created',
    create_first_version: 'Create your first dinosaur version to start managing configurations.',
    duplicate: 'Duplicate',
    edit: 'Edit',
    delete: 'Delete',
    hide_details: 'Hide Details',
    show_details: 'Show Details',
    components_count: 'Components ({count})',
    notes: 'Notes',
    no_components_configured: 'No components configured for this version.',
    no_notes_version: 'No notes for this version.',
    units_made: 'Units Made ({count})',
    no_dinosaurs_registered_version: 'No dinosaurs have been registered with this version yet.',
    create_editable_copy: 'Create a new editable copy of this version',
    cannot_delete_version_has_dinosaurs: 'Cannot delete a version that has dinosaurs registered to it.',
    // Additional Dinosaur Versions translations
    cannot_delete_version_has_dinosaurs_with_count: 'Cannot delete this version because it has {count} dinosaurs registered. Delete the dinosaurs first.',
    confirm_delete_version: 'Are you sure you want to delete version "{name}"? This action cannot be undone.',
    enter_duplicate_version_name: 'Enter the name for the duplicated version:',
    copy: 'Copy',
    enter_different_name_duplicate: 'Please enter a different name for the duplicate version.',
    duplicated_from: 'Duplicated from',
    version_duplicated_successfully: 'Version "{newName}" has been created successfully as a copy of "{originalName}".',
    error_duplicating_version: 'Error creating the duplicate version. Please try again.',
    component_already_added: 'Component "{name}" has already been added to this version.',
    select_components_for_version: 'Select the components needed for this version (specific batches will be selected in WIP Loading)',
    no_tracking: 'No Tracking',
    batches_selected_in_wip: 'Specific batches are selected in WIP Loading',
    created_on: 'Created on',
    
    // Devices page
    device_registration_station: 'Device Registration Station',
    register_devices_step_by_step: 'Register new devices step by step with guided assistance.',
    device_registration_assistant: 'Device Registration Assistant',
    select_dinosaur_version: '1. Select Dinosaur Version',
    scan_device_id: '2. Scan or Enter Device ID',
    scan_serial_numbers: '3. Scan Serial Numbers',
    additional_notes_optional_device: '4. Additional Notes (Optional)',
    confirm_and_register: '5. Confirm and Register',
    register_device: 'Register Device',
    scan_or_enter_device_id: 'Scan or enter device ID...',
    scan_serial_number: 'Scan serial number...',
    no_serial_components_required: '3. No Serial Components Required',
    this_version_no_serials: 'This version does not require serial number scanning.',
    continue_to_notes: 'Continue to Notes',
    device_registered_successfully: 'Device registered successfully: ID',
    showing_x_of_y_devices: 'Showing {filtered} of {total} devices',
    ready: 'Ready',
    used: 'Used',
    defective: 'Defective',
    search_by_id_notes_serials: 'Search by ID, notes or serial numbers...',
    no_devices_found: 'No devices found',
    devices_will_appear: 'Devices will appear here once you register the first one',
    
    // Sales page
    sales_registration_station: 'Sales Registration Station',
    editing_sale: 'Editing Sale',
    modify_sale_details_prompt: 'Modify the details of this sale.',
    register_sales_quickly: 'Register sales quickly by scanning the RFID of each dinosaur.',
    order_number: 'Order Number',
    scan_dinosaur_rfid: 'Scan Dinosaur RFID',
    rfid_detected: 'RFID detected',
    waiting_for_scan_placeholder: 'Waiting for RFID scan...',
    scanning_in_progress: 'Scanning... {current}/{total} characters',
    confirmed_rfid_label: 'Confirmed RFID:',
    additional_notes_optional: 'Additional Notes (Optional)',
    sale_comments_placeholder: 'Comments about the sale, special requests, etc.',
    rfid_issue_title: 'RFID Issue Detected',
    continue_anyway_button: 'Continue Anyway',
    cancel_button: 'Cancel',
    register_sale_button: 'Register Sale',
    update_sale_button: 'Update Sale',
    cancel_edit_button: 'Cancel Edit',
    sale_updated_success: 'Sale updated:',
    sale_registered_success: 'Sale registered:',
    sale_deleted_success: 'Sale deleted:',
    with_rfid_label: 'with RFID',
    recent_sales_title: 'Recent Sales',
    no_recent_sales_message: 'No recent sales to display.',
    scan_rfid_required: 'Please scan a valid RFID code to register the sale.',
    order_number_required: 'Order number is required.',
    interference_detected: 'Interference detected! Multiple RFID tags are too close. Please separate them and scan again.',
    rfid_too_long: 'Invalid scan. RFID code is too long ({length} characters, expected {expected}).',
    dino_not_found_with_history: 'Dinosaur with RFID {rfid} not found in inventory. However, it was previously sold in order {orderNumber} on {formattedSaleDate} ({timeAgo}). {count, plural, one {There is # sale} other {There are # sales}} registered with this RFID.',
    dino_not_found_no_history: 'Dinosaur with RFID {rfid} not found in inventory and no previous sales found.',
    dino_already_sold: 'This dinosaur was already sold in order {orderNumber} on {formattedSaleDate} ({timeAgo}). {count, plural, one {There is # sale} other {There are # sales}} registered with this RFID.',
    dino_not_available: 'Dinosaur with RFID {rfid} is not available (current status: {status}).',
    multiple_available_dinos_warning: 'Warning: Multiple available dinosaurs found with RFID {rfid}',
    
    // Inventory Management
    inventory_management_hub: 'Inventory Management Hub',
    central_hub_for_inventory: 'Your central hub for purchase orders, receiving, and stock control.',
    purchase_orders: 'Purchase Orders',
    receiving: 'Receiving',
    stock_control: 'Stock Control',
    production_plan: 'Production Plan',
    
    // PO Sub-page
    create_and_manage_pos: 'Create and manage purchase orders for your components.',
    create_po: 'Create Purchase Order',
    no_pos_found: 'No purchase orders found',
    create_first_po: 'Create your first purchase order to get started.',
    ordered_on: 'Ordered on',
    pending: 'Pending',
    in_transit: 'In Transit',
    partially_received: 'Partially Received',
    completed: 'Completed',
    cancelled: 'Cancelled',
    
    // Receiving Sub-page
    receive_items_against_po: 'Receive items against open purchase orders to update your stock.',
    select_po_to_receive: 'Select a PO to receive items',
    no_open_pos: 'No Open Purchase Orders',
    create_po_to_receive: 'Create a purchase order first to start receiving items',
    progress: 'Progress',
    items: 'items',
    receiving_items_for: 'Receiving Items for',
    select_po_to_start_receiving: 'Select a Purchase Order to Start',
    click_on_po_card_above: 'Click on a PO card above to view its items and start receiving',
    
    // Stock Control Sub-page
    view_current_inventory_levels: 'View current inventory levels for all components.',
    
    // Production Plan Sub-page
    plan_dinosaur_production: 'Plan your dinosaur production based on available component stock.',

    // BOM Management page
    bom_interactive_viewer: 'BOM Interactive Viewer',
    interactive_bom_view: 'Interactive Bill of Materials view',
    debug_mode: 'Debug Mode',
    exit_debug: 'Exit Debug',
    save: 'Save',
    reset: 'Reset',
    dinosaur_version: 'Dinosaur Version',
    select_version: 'Select version',
    production_target: 'Production Target',
    production_quantity_placeholder: 'Quantity to produce...',
    debug_mode_activated: 'Debug Mode Activated',
    drag_points: 'Drag the points on the image to reposition them',
    save_when_finished: 'Click "Save" when you have finished positioning all the points',
    currently_moving: 'Currently moving: {component}',
    bill_of_materials: 'Bill of Materials ({count} components)',
    select_version_to_view: 'Select a version to view the components',
    status: 'Status',
    component: 'Component',
    current_stock: 'Current Stock',
    required: 'Required',
    shortage: 'Shortage',
    supplier: 'Supplier',
    exploded_view: 'Exploded View',
    total_required: 'Total Required',
    current_stock_total: 'Current Stock',
    total_shortage: 'Total Shortage',
    ready_to_produce: 'Ready to Produce',
    
    // Database Admin page
    database_administration: 'Database Administration',
    inspect_analyze_raw_data: 'Inspect and analyze RAW data stored in entities',
    rate_limit_active: 'Rate Limit Active',
    error: 'Error',
    api_rate_limited: 'The API is rate-limited. Please wait before making more requests.',
    entity: 'Entity',
    search: 'Search',
    search_all_fields: 'Search in all fields...',
    update: 'Update',
    waiting: 'Waiting...',
    loading: 'Loading...',
    export_json: 'Export JSON',
    total_records: 'Total Records:',
    filtered: 'Filtered:',
    total_fields: 'Total Fields:',
    unmapped_fields: 'Unmapped Fields:',
    unmapped_fields_found: 'Unmapped fields found in {entity}:',
    raw_data: 'Data from {entity} ({count} records)',
    loading_data: 'Loading data...',
    error_loading_data: 'Error loading data',
    no_records_found: 'No records found',
    view_json: 'View JSON',
    json_raw: 'JSON Raw - {entity} #{id}',
    
    // Quality Control page
    quality_control_station: 'Quality Control Station',
    test_device_quality: 'Test device and dinosaur quality and functionality',
    select_qc_type: 'Select Quality Control Type',
    qc_by_device: 'QC by Device',
    qc_by_dinosaur: 'QC by Dinosaur',
    qc_device_description: 'Perform tests directly on a device using its unique ID.',
    qc_dinosaur_description: 'Start the QC process for an assembled dinosaur using its RFID.',
    back_to_selection: 'Back to Selection',
    select_device_for_qc: 'Select Device for QC',
    select_dinosaur_for_qc: 'Select Dinosaur for QC',
    enter_device_id: 'Enter device ID...',
    scan_enter_dinosaur_rfid: 'Scan or enter dinosaur RFID...',
    dinosaur_selected: 'Selected Dinosaur',
    rfid: 'RFID',
    device_to_test: 'Device to Test',
    current_status: 'Current Status',
    assembled: 'Assembled',
    last_qc: 'Last QC',
    never: 'Never',
    start_qc_tests: 'Start Quality Control Tests',
    running_tests: 'Running Tests...',
    test_progress: 'Test Progress',
    test_x_of_y: 'Test {current} of {total}',
    percent_completed: '{percent}% completed',
    action_required: 'ACTION REQUIRED!',
    action_completed: 'Action Completed',
    qc_results: 'QC Results',
    device_approved: 'DEVICE APPROVED',
    device_failed: 'DEVICE FAILED',
    tests_passed: '{passed} of {total} tests passed',
    continue_save_results: 'Continue - Save Results',
    complete_event_log: 'Complete Event Log',
    showing_all_events: 'Showing all {count} recorded events',
    view_details: 'View details',
    device_not_found_qc: 'Device not found. Please check the ID and try again.',
    dinosaur_not_found_qc: 'Dinosaur not found. Please check the RFID and try again.',
    no_device_id_associated: 'This dinosaur does not have an associated device ID.',
    
    // Search page  
    global_search: 'Global Search',
    search_across_inventory: 'Search across your entire inventory system',
    search_placeholder: 'Search by RFID, device ID, order number, component name, etc...',
    search_results: 'Search Results',
    no_results_found: 'No results found',
    try_different_search: 'Try a different search term',
    dinosaur_result: 'Dinosaur',
    device_result: 'Device',
    sale_result: 'Sale',
    component_result: 'Component',
    version_result: 'Version',

    // User Management
    user_management: 'User Management',
    user_management_title: 'User Management',
    user_management_subtitle: 'Edit user details and access permissions.',
    user_list: 'User List',
    invite_users_notice: 'New users must be invited through the platform settings.',
    user: 'User',
    user_code: 'User Code',
    role: 'Role',
    permissions: 'Permissions',
    no_permissions_assigned: 'No permissions assigned',
    edit_user_permissions_for: 'Edit permissions for',
    description: 'Description',
    access_permissions: 'Access Permissions',
    save_changes: 'Save Changes',
    admin: 'Admin',
    access_denied: 'Access Denied',
    admin_only_access: 'This section is available for administrators only.',
    error_updating_user: 'Error updating user',

    // Operator Management
    operator_management: 'Operator Management',
    operator_management_title: 'Operator Management',
    operator_management_subtitle: 'Manage operator codes and access permissions.',
    add_operator: 'Add Operator',
    operator_name: 'Operator Name',
    operator_code_4_digits: 'Access Code (4 digits)',
    operator_code_4_digits_validation: 'Code must be exactly 4 numeric digits',
    operator_login_prompt: 'Enter your operator code',
    operator_code_invalid: 'Invalid operator code',
    operator_login_error: 'Login error',
    no_operators_found: 'No operators found',
    add_first_operator_prompt: 'Add your first operator to get started.',
    edit_operator_for: 'Edit Operator: {name}',
    add_operator_desc: 'Create a new operator with 4-digit access code',
    edit_operator_desc: 'Modify operator data and permissions',
    operator: 'Operator',
    logout: 'Logout',
    code: 'Code',
    error_saving_operator: 'Error saving operator',
    error_deleting_operator: 'Error deleting operator',
    confirm_delete_operator: 'Are you sure you want to delete this operator? This action cannot be undone.',
    // Operator Management - Additional
    administrator: 'Administrator',
    administrator_description: 'Administrators have full access to all sections and can manage other operators.',
    admin_has_all_permissions: 'Administrators automatically have access to all sections.',
    operator_role_description_placeholder: 'E.g., Assembly line operator',
    admin_verification: 'Admin Verification',
    enter_admin_pin_to_view: 'Enter admin PIN to view the code',
    admin_pin: 'Admin PIN',
    verify: 'Verify',
    incorrect_admin_pin: 'Incorrect admin PIN',

    // Dinosaur Form
    edit_dinosaur: 'Edit Dinosaur',
    slack_bot: 'Slack Bot',

    // WIP Loading System
    wip_loading: 'WIP Loading',
    wip_loading_station: 'WIP Loading Station',
    wip_loading_subtitle: 'Daily batch loading for production - Preparation before assembly',
    active_wip_today: 'Active WIP - Today',
    complete_wip: 'Complete WIP',
    completed: 'Completed',
    units: 'units',
    loaded_by: 'Loaded By',
    batches_loaded: 'Batches Loaded',
    available_stock: 'avail.',
    no_active_wip_warning: '⚠️ No active WIP Loading for today. Operators will NOT be able to register devices until WIP Loading is completed.',
    create_wip_loading_today: 'Create WIP Loading for Today',
    wip_loading_description: 'Select the version and scan the batches that will be used in production',
    version_to_assemble: 'Version to Assemble*',
    select_version_placeholder: 'Select version...',
    scan_batch: 'Scan Batch',
    scan_batch_qr_placeholder: 'Scan batch QR code...',
    batch_components_to_scan: 'Batch Components to Scan ({scanned}/{total})',
    all_scanned: 'All scanned',
    pending: 'Pending',
    complete_wip_loading: 'Complete WIP Loading',
    completing_wip: 'Completing WIP...',
    no_batch_components: 'This version does not have components that require batch scanning. You can create the WIP directly.',
    batch_not_found: '❌ Batch "{batch}" not found in inventory',
    component_not_required: '❌ Component "{component}" is not required in this version',
    already_scanned: '⚠️ A batch for "{component}" has already been scanned',
    no_stock_available: '❌ Batch "{batch}" has no available stock ({quantity} units)',
    batch_scanned_successfully: '✅ Batch for "{component}" scanned successfully',
    remove: 'Remove',
    creating_wip: 'Creating WIP Loading...',
    please_select_version: 'Please select a version',
    please_scan_all_batches: 'Please scan all required batches before completing WIP Loading',
    error_creating_wip: 'Error creating WIP Loading:',
    error_completing_wip: 'Error completing WIP:',
    confirm_complete_wip: 'Mark today\'s WIP Loading as complete? This will close the production session.',
    // WIP Loading - additional translations
    quantity_to_load: 'Quantity to Load',
    quantity_to_load_placeholder: 'Enter quantity...',
    components_to_load: 'Components to Load',
    select_component_from_list: 'Select a component from the list on the left to start loading',
    loading_details: 'Loading Details',
    bins_loaded: 'Bins Loaded',
    no_bins_loaded_yet: 'No bins loaded yet for this component',
    // WIP Loading - bin replacement
    bin_already_exists_for_component: 'This component already has a bin loaded',
    replace_existing_bin_warning: 'Component "{componentName}" already has bin "{existingBin}" loaded with {quantity} units from PO {poNumber}.\n\nDo you want to replace it with the new bin "{newBin}"?',
    bin_replaced_successfully: 'Bin replaced successfully',

    // SKU System
    sku_base: 'SKU Base (Code Name)',
    version_number: 'Version Number',
    color_name_placeholder: 'Color name (e.g., Quartz)',
    color_code_placeholder: 'Code (e.g., QU)',
    sku_preview: 'Final SKU',
    color_already_exists: 'This color or code already exists',

    // Shipping section
    shipping: 'Shipping',
    shipping_station: 'Shipping Station',
    register_shipments_tracking: 'Register shipments and track packages to USA',
    new_shipment: 'New Shipment',
    scan_dinosaurs_add_tracking: 'Scan dinosaurs and add tracking information',
    tracking_number: 'Tracking Number',
    scan_dinosaur_rfids: 'Scan Dinosaur RFIDs',
    scan_or_enter_rfid: 'Scan or enter RFID...',
    scanned_dinosaurs: 'Scanned Dinosaurs',
    shipment_notes_placeholder: 'Carrier, special instructions, etc...',
    register_shipment: 'Register Shipment',
    registering: 'Registering',
    recent_shipments: 'Recent Shipments',
    tracking: 'Tracking',
    shipped_by: 'Shipped by',
    date: 'Date',
    dinosaurs_in_shipment: 'Dinosaurs in this Shipment',
    no_shipments_registered: 'No shipments registered',
    start_by_registering_first_shipment: 'Start by registering your first shipment',
    tracking_number_required: 'Tracking number is required',
    at_least_one_rfid_required: 'At least one dinosaur RFID is required',
    shipment_registered_successfully: 'Shipment registered successfully!',
    error_registering_shipment: 'Error registering shipment',
    confirm_delete_shipment: 'Are you sure you want to delete shipment {tracking}?',
    error_deleting_shipment: 'Error deleting shipment',
    rfid_already_scanned: 'This RFID has already been scanned',
    dinosaur_not_found_rfid: 'Dinosaur with RFID {rfid} not found',
    dinosaur_not_sold_warning: 'Warning: Dinosaur {rfid} status is "{status}" (not sold)',
    rfid_scanned_successfully: 'RFID {rfid} scanned successfully',
    error_verifying_dinosaur: 'Error verifying dinosaur',

    // Christmas Countdown
    countdown_to_christmas: 'Countdown to Christmas',
    time_until_christmas: 'Time until Christmas Day',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    merry_christmas: '🎄 Merry Christmas! 🎄',
    its_christmas: "It's Christmas!",
    merry_christmas_message: 'Wishing you a wonderful Christmas filled with joy and happiness!',
    christmas_message_far: '🎅 Santa is getting his sleigh ready!',
    christmas_message_soon: '🎁 Christmas is coming soon! Time to get festive!',
    christmas_message_very_soon: '⛄ Almost here! The magic of Christmas is in the air!',

    // QuickQC translations
    quick_qc_station: 'Quick QC Station',
    quick_qc_subtitle: 'Fast quality control test for ESP32',
    ensure_device_on_range: 'Make sure the ESP32 device is on and within range',
    searching_device: 'Searching for device...',
    start_qc_test: 'Start QC Test',
    running_tests: 'Running Tests',
    test_audio: 'Audio Test',
    test_mic_basic: 'Basic Mic Test',
    test_mic_lr_balance: 'L/R Balance Mic Test',
    test_battery: 'Battery Test',
    adjust_volume: 'Volume Adjustment',
    event_log: 'Event Log',
    test_another_device: 'Test Another Device',

    // New additions for WIPLoading date error
    unknown_date: 'Unknown date',
    invalid_date: 'Invalid date',

    // Purchase Order Form translations
    supplier_name: 'Supplier Name',
    supplier_name_placeholder: 'Supplier name...',
    invoice_number: 'Invoice Number',
    invoice_number_placeholder: 'INV-2024-001...',
    tracking_number_po: 'Tracking Number', // Renamed to avoid collision with sales/shipping
    tracking_number_placeholder: '1Z999AA1234567890...',
    estimated_delivery: 'Estimated delivery',
    items_to_order: 'Items to Order',
    component_po: 'Component', // Renamed to avoid collision with general 'component'
    select_component_po: 'Select component', // Renamed to avoid collision
    quantity_po: 'Quantity', // Renamed to avoid collision
    additional_notes_po: 'Additional Notes', // Renamed to avoid collision
    additional_notes_placeholder_po: 'Special instructions, comments...', // Renamed to avoid collision
    intelligent_document_processing: 'Intelligent Document Processing',
    upload_po_photo_description: 'Upload a photo of your purchase order and AI will automatically extract all information.',
    upload_po_photo: 'Upload Purchase Order Photo',
    processing: 'Processing...',
    creating: 'Creating...',
    saving: 'Saving...',
    save_changes: 'Save Changes',
    create_purchase_order: 'Create Purchase Order',
    edit_purchase_order: 'Edit Purchase Order',
    document_processed_successfully: 'Document processed successfully! Review the extracted information and adjust if necessary.',
    error_processing_document: 'Error processing document. Please try again or enter data manually.',
    // Purchase Order Form - Price fields
    unit_price: 'Unit Price',
    total_price: 'Total Price',
    unit_price_placeholder: 'Price per unit...',
    total_price_placeholder: 'Total price...',
    price_required: 'Price is required',
    subtotal: 'Subtotal',
    grand_total: 'Grand Total',
    batch_info: 'Batch Info',
    batch_info_placeholder: 'Supplier batch number, production date, internal codes...',
    batch_info_description: 'Internal supplier information about this batch (optional)',
    
    // Bin Number (replacing Batch)
    bin_number: 'Bin Number',
    scan_bin_number: 'Scan Bin Number',
    bin_number_placeholder: 'Scan bin number...',
    select_purchase_order: 'Select Purchase Order',
    link_bin_to_po: 'Link Bin to PO',
    bin_linked_successfully: 'Bin linked successfully',
    bin_already_loaded: 'This bin is already loaded',
    no_matching_pos: 'No purchase orders found with this component',
    quantity_in_po: 'Qty in PO',
    already_received: 'Already Received',
    available_in_po: 'Available',
    select_po_with_component: 'Select a PO that contains this component',
    bins_to_load: 'Bins to Load',
    bin_info: 'Bin Info',
    linked_to_po: 'Linked to PO',

    scan_or_select_po: 'Scan or Select PO',
    scan_po_number: 'Scan PO Number',
    scan_po_placeholder: 'Scan PO number...',
    or_select_from_list: 'Or select from available POs:',
    no_pos_with_component: 'No purchase orders found with this component',
    
    scan: 'Scan',
    and: 'and',
    more_items: 'more items',
    total: 'Total',
    no_location: 'No location',
    select_warehouse: 'Select warehouse',
    active_warehouse: 'Active Warehouse',
    no_warehouses_configured: 'No warehouses configured',
    create_warehouse: 'Create warehouse',
    warehouse: 'Warehouse',
  },
  es: {
    // Navigation and layout
    dashboard: 'Tablero',
    components: 'Componentes',
    dinosaurs: 'Dinosaurios',
    devices: 'Dispositivos',
    sales: 'Ventas',
    search: 'Búsqueda',
    bom_management: 'Gestión de BOM',
    inventory_management: 'Gestión Inventario',
    odoo_sync: 'Sincro Odoo',
    versions: 'Versiones',
    quality_control: 'Control de Calidad',
    db_admin: 'Admin BD',
    management: 'Gestión',
    quick_stats: 'Estadísticas',
    inventory_manager: 'Gestor de Inventario',
    
    // Dashboard
    dashboard_title: 'Tablero DinoTrack',
    dashboard_subtitle: 'Tu panel de control de inventario de dinosaurios',
    total_components: 'Total Componentes',
    total_dinosaurs: 'Total Dinosaurios',
    total_sales: 'Total Ventas',
    available_dinos: 'Dinos Disponibles',
    low_stock: 'Stock Bajo',
    sales_this_week: 'Ventas Esta Semana',
    recent_dinosaurs: 'Dinosaurios Recientes',
    critical_components: 'Componentes Críticos',
    all_components_sufficient_stock: 'Todos los componentes tienen stock suficiente',
    no_dinosaurs_registered: 'No hay dinosaurios registrados',
    
    // Components page
    component_management: 'Gestión de Componentes',
    manage_parts_components_inventory: 'Gestiona tu inventario de partes y componentes',
    add_component: 'Agregar Componente',
    search_components_placeholder: 'Buscar componentes por nombre, lote o serie...',
    category: 'Categoría',
    tracking: 'Seguimiento',
    all: 'Todos',
    by_batch: 'Por Lote',
    by_unit: 'Por Unidad',
    chips: 'Chips',
    batteries: 'Baterías',
    sensors: 'Sensores',
    motors: 'Motores',
    structures: 'Estructuras',
    others: 'Otros',
    no_components_registered: 'No hay componentes registrados',
    start_adding_first_component: 'Comienza agregando tu primer componente al inventario',
    confirm_delete_component: '¿Estás seguro de que quieres eliminar el componente "{componentName}"? Esta acción no se puede deshacer.',
    
    // Dinosaurs page
    dinosaur_registration_station: 'Estación de Registro de Dinosaurios',
    register_dinosaurs_step_by_step: 'Registra dinosaurios con un asistente guiado paso a paso.',
    assembly_station: 'Estación de Ensamblaje',
    registration_assistant: 'Asistente de Registro',
    select_dinosaur_version_step: '1. Selecciona la Versión del Dinosaurio',
    select_color_step: '2. Selecciona el Color',
    scan_plush_rfid_step: '3. Escanea el RFID del Peluche',
    scan_device_id_step: '4. Escanea el ID del Dispositivo',
    additional_notes_step: '5. Notas Adicionales (Opcional)',
    confirm_register_step: '6. Confirmar y Registrar',
    choose_version: 'Elegir versión...',
    select_color: 'Seleccionar color...',
    waiting_rfid_scan: 'Esperando escaneo de RFID...',
    device_id_placeholder: 'ID del dispositivo...',
    special_observations_placeholder: 'Observaciones especiales, modificaciones, etc...',
    continue: 'Continuar',
    back: 'Atrás',
    register_dinosaur: 'Registrar Dinosaurio',
    version: 'Versión',
    color: 'Color',
    device_id: 'ID del Dispositivo',
    step_x_of_y: 'Paso {current} de {total}',
    search_rfid_device_placeholder: 'Buscar por RFID o ID de dispositivo...',
    total_dinosaurs: 'Total: {count} dinosaurios',
    all_statuses: 'Todos los Estados',
    all_colors: 'Todos los Colores',
    all_versions: 'Todas las Versiones',
    available: 'Disponible',
    sold: 'Vendido',
    maintenance: 'Mantenimiento',
    damaged: 'Dañado',
    unverified: 'Sin verificar',
    pink: 'Rosa',
    teal: 'Teal',
    lavender: 'Lavanda',
    green: 'Verde',
    interference_detected_rfids: 'Interferencia detectada! Múltiples etiquetas RFID están muy cerca. Por favor sepáralas y escanea de nuevo.',
    missing_data_restart_process: 'Faltan datos requeridos. Por favor reinicia el proceso de registro.',
    device_not_found_warning: 'Dispositivo con ID "{deviceId}" no encontrado en estado listo. ¿Quieres registrar de todos modos?',
    error_registering_dinosaur: 'Error registrando dinosaurio. Por favor intenta de nuevo.',
    force_register_warning_note: 'ADVERTENCIA: Registro forzado. El dispositivo {deviceId} no se encontró en estado listo.',
    error_force_register: 'Error durante el registro forzado. Por favor intenta de nuevo.',
    cannot_delete_sold_dinosaur: 'No se puede eliminar un dinosaurio que ya ha sido vendido.',
    confirm_delete_dinosaur: '¿Estás seguro de que quieres eliminar el dinosaurio con RFID {rfid_code}? Esta acción no se puede deshacer.',
    dinosaur_registered_successfully_rfid: '¡Dinosaurio registrado exitosamente! RFID:',
    device: 'Dispositivo',
    assembled_by: 'Ensamblado Por',
    device_defective_warning: 'El dispositivo {deviceId} está marcado como defectuoso. ¿Quieres registrar de todos modos?',
    qc_failed_warning: 'El dispositivo {deviceId} falló pruebas de QC: {failedTests}. ¿Quieres registrar de todos modos?',
    qc_not_tested_warning: 'El dispositivo {deviceId} no ha sido probado en QC. ¿Quieres registrar de todos modos?',
    device_not_ready_warning: 'El dispositivo {deviceId} está en estado "{status}", no listo. ¿Quieres registrar de todos modos?',
    force_register_note_defective: 'ADVERTENCIA: Registro forzado. El dispositivo {deviceId} está marcado como defectuoso.',
    force_register_note_qc_failed: 'ADVERTENCIA: Registro forzado. El dispositivo {deviceId} falló pruebas de QC: {failedTests}.',
    force_register_note_qc_not_tested: 'ADVERTENCIA: Registro forzado. El dispositivo {deviceId} no ha sido probado en QC.',
    force_register_note_not_ready: 'ADVERTENCIA: Registro forzado. El dispositivo {deviceId} está en estado no listo.',
    force_register_note_device_not_found: 'ADVERTENCIA: Registro forzado. El dispositivo {deviceId} no fue encontrado en el inventario.',
    continue_anyway: 'Continuar de todos modos',
    cancel_and_review: 'Cancelar y Revisar',
    
    // Dinosaur Versions page
    dinosaur_versions: 'Versiones de Dinosaurios',
    create_manage_configurations: 'Crear y gestionar configuraciones y recetas de dinosaurios',
    create_version: 'Crear Versión',
    edit_version: 'Editar Versión',
    create_new_version: 'Crear Nueva Versión',
    model_name: 'Nombre del Modelo',
    available_colors: 'Colores Disponibles',
    write_color_placeholder: 'Escribir color (ej., rosa)',
    components_configuration: 'Configuración de Componentes',
    option_1_scan_batch: 'Opción 1: Escanea el código de barras de un lote o número de serie del componente para agregarlo.',
    scan_batch_serial_placeholder: 'Escanear lote o número de serie...',
    option_2_select_manually: 'Opción 2: Selecciona un componente manualmente.',
    select_component: 'Seleccionar componente',
    select_batch: 'Seleccionar lote',
    add: 'Agregar',
    added_components: 'Componentes Agregados ({count})',
    batch: 'Lote',
    individual: 'Individual',
    version_notes: 'Notas de la Versión',
    version_notes_placeholder: 'Características especiales, modificaciones, etc...',
    cancel: 'Cancelar',
    saving: 'Guardando...',
    saved: 'Guardado',
    save_error: 'Error al guardar',
    no_versions_created: 'No hay versiones creadas',
    create_first_version: 'Crea tu primera versión de dinosaurio para empezar a gestionar configuraciones.',
    duplicate: 'Duplicar',
    edit: 'Editar',
    delete: 'Eliminar',
    hide_details: 'Ocultar Detalles',
    show_details: 'Mostrar Detalles',
    components_count: 'Componentes ({count})',
    notes: 'Notas',
    no_components_configured: 'No hay componentes configurados para esta versión.',
    no_notes_version: 'No hay notas para esta versión.',
    units_made: 'Unidades Fabricadas ({count})',
    no_dinosaurs_registered_version: 'Aún no se han registrado dinosaurios con esta versión.',
    create_editable_copy: 'Crear una nueva copia editable de esta versión',
    cannot_delete_version_has_dinosaurs: 'No se puede eliminar una versión que tiene dinosaurios registrados.',
    // Additional Dinosaur Versions translations
    cannot_delete_version_has_dinosaurs_with_count: 'No puedes eliminar esta versión porque tiene {count} dinosaurios registrados. Elimina primero los dinosaurios.',
    confirm_delete_version: '¿Estás seguro de que quieres eliminar la versión "{name}"? Esta acción no se puede deshacer.',
    enter_duplicate_version_name: 'Ingresa el nombre para la versión duplicada:',
    copy: 'Copia',
    enter_different_name_duplicate: 'Por favor ingresa un nombre diferente para la versión duplicada.',
    duplicated_from: 'Duplicado de',
    version_duplicated_successfully: 'La versión "{newName}" se ha creado exitosamente como copia de "{originalName}".',
    error_duplicating_version: 'Error al crear la versión duplicada. Por favor intenta de nuevo.',
    component_already_added: 'El componente "{name}" ya ha sido agregado a esta versión.',
    select_components_for_version: 'Selecciona los componentes que se necesitan para esta versión (los batches específicos se seleccionarán en WIP Loading)',
    no_tracking: 'Sin seguimiento',
    batches_selected_in_wip: 'Los batches específicos se seleccionan en WIP Loading',
    created_on: 'Creado el',
    
    // Devices page  
    device_registration_station: 'Estación de Registro de Dispositivos',
    register_devices_step_by_step: 'Registre nuevos dispositivos paso a paso de forma guiada.',
    device_registration_assistant: 'Asistente de Registro de Dispositivo',
    select_dinosaur_version: '1. Selecciona la Versión del Dinosaurio',
    scan_device_id: '2. Escanea o Ingresa el ID del Dispositivo',
    scan_serial_numbers: '3. Escanea los Números de Serie',
    additional_notes_optional_device: '4. Notas Adicionales (Opcional)',
    confirm_and_register: '5. Confirmar y Registrar',
    register_device: 'Registrar Dispositivo',
    scan_or_enter_device_id: 'Escanear o ingresar ID del dispositivo...',
    scan_serial_number: 'Escanear número de serie...',
    no_serial_components_required: '3. Sin Componentes de Serie Requeridos',
    this_version_no_serials: 'Esta versión no requiere escaneo de números de serie.',
    continue_to_notes: 'Continuar a Notas',
    device_registered_successfully: 'Dispositivo registrado exitosamente: ID',
    showing_x_of_y_devices: 'Mostrando {filtered} de {total} dispositivos',
    ready: 'Listo',
    used: 'Usado',
    defective: 'Defectuoso',
    search_by_id_notes_serials: 'Buscar por ID, notas o números de serie...',
    no_devices_found: 'No se encontraron dispositivos',
    devices_will_appear: 'Los dispositivos aparecerán aquí una vez que registres el primero',
    
    // Sales page
    sales_registration_station: 'Estación de Registro de Ventas',
    editing_sale: 'Editando Venta',
    modify_sale_details_prompt: 'Modifica los detalles de esta venta.',
    register_sales_quickly: 'Registra ventas rápidamente escaneando el RFID de cada dinosaurio.',
    order_number: 'Número de Orden',
    scan_dinosaur_rfid: 'Escanear RFID del Dinosaurio',
    rfid_detected: 'RFID detectado',
    waiting_for_scan_placeholder: 'Esperando escaneo de RFID...',
    scanning_in_progress: 'Escaneando... {current}/{total} caracteres',
    confirmed_rfid_label: 'RFID Confirmado:',
    additional_notes_optional: 'Notas Adicionales (Opcional)',
    sale_comments_placeholder: 'Comentarios sobre la venta, solicitudes especiales, etc.',
    rfid_issue_title: 'Problema con RFID Detectado',
    continue_anyway_button: 'Continuar de todos modos',
    cancel_button: 'Cancelar',
    register_sale_button: 'Registrar Venta',
    update_sale_button: 'Actualizar Venta',
    cancel_edit_button: 'Cancelar Edición',
    sale_updated_success: 'Venta actualizada:',
    sale_registered_success: 'Venta registrada:',
    sale_deleted_success: 'Venta eliminada:',
    with_rfid_label: 'con RFID',
    recent_sales_title: 'Ventas Recientes',
    no_recent_sales_message: 'No hay ventas recientes para mostrar.',
    scan_rfid_required: 'Por favor escanea un código RFID válido para registrar la venta.',
    order_number_required: 'El número de orden es requerido.',
    interference_detected: 'Interferencia detectada! Múltiples etiquetas RFID están muy cerca. Por favor sepáralas y escanea de nuevo.',
    rfid_too_long: 'Escaneo inválido. El código RFID es muy largo ({length} caracteres, se esperaban {expected}).',
    dino_not_found_with_history: 'Dinosaurio con RFID {rfid} no encontrado en inventario. Sin embargo, fue vendido previamente en la orden {orderNumber} el {formattedSaleDate} ({timeAgo}). {count, plural, one {Hay # venta} other {Hay # ventas}} registradas con este RFID.',
    dino_not_found_no_history: 'Dinosaurio con RFID {rfid} no encontrado en inventario y no se encontraron ventas previas.',
    dino_already_sold: 'Este dinosaurio ya fue vendido en la orden {orderNumber} el {formattedSaleDate} ({timeAgo}). {count, plural, one {Hay # venta} other {Hay # ventas}} registradas con este RFID.',
    dino_not_available: 'Dinosaurio con RFID {rfid} no está disponible (estado actual: {status}).',
    multiple_available_dinos_warning: 'Advertencia: Se encontraron múltiples dinosaurios disponibles con RFID {rfid}',
    
    // Inventory Management
    inventory_management_hub: 'Centro de Gestión de Inventario',
    central_hub_for_inventory: 'Tu centro de mando para órdenes de compra, recepción y control de stock.',
    purchase_orders: 'Órdenes de Compra',
    receiving: 'Recepción',
    stock_control: 'Control de Stock',
    production_plan: 'Plan de Producción',
    
    // PO Sub-page
    create_and_manage_pos: 'Crea y gestiona las órdenes de compra para tus componentes.',
    create_po: 'Crear Orden de Compra',
    no_pos_found: 'No se encontraron órdenes de compra',
    create_first_po: 'Crea tu primera orden de compra para comenzar.',
    ordered_on: 'Ordenado el',
    pending: 'Pendiente',
    in_transit: 'En Tránsito',
    partially_received: 'Parcialmente Recibido',
    completed: 'Completado',
    cancelled: 'Cancelado',
    
    // Receiving Sub-page
    receive_items_against_po: 'Recibe artículos contra órdenes de compra abiertas para actualizar tu stock.',
    select_po_to_receive: 'Selecciona una OC para recibir ítems',
    no_open_pos: 'Sin Órdenes de Compra Abiertas',
    create_po_to_receive: 'Crea una orden de compra primero para empezar a recibir artículos',
    progress: 'Progreso',
    items: 'artículos',
    receiving_items_for: 'Recibiendo Artículos para',
    select_po_to_start_receiving: 'Selecciona una Orden de Compra para Comenzar',
    click_on_po_card_above: 'Haz clic en una tarjeta de OC arriba para ver sus artículos y comenzar a recibir',

    // Stock Control Sub-page
    view_current_inventory_levels: 'Visualiza los niveles de inventario actuales de todos los componentes.',
    
    // Production Plan Sub-page
    plan_dinosaur_production: 'Planifica tu producción de dinosaurios basándote en el stock de componentes disponible.',

    // BOM Management page
    bom_interactive_viewer: 'Visor Interactivo de BOM',
    interactive_bom_view: 'Vista interactiva de la Lista de Materiales',
    debug_mode: 'Modo Debug',
    exit_debug: 'Salir Debug',
    save: 'Guardar',
    reset: 'Reset',
    dinosaur_version: 'Versión del Dinosaurio',
    select_version: 'Seleccionar versión',
    production_target: 'Objetivo de Producción',
    production_quantity_placeholder: 'Cantidad a producir...',
    debug_mode_activated: 'Modo Debug Activado',
    drag_points: '🖱️ Arrastra los puntos en la imagen para reposicionarlos',
    save_when_finished: '💾 Haz clic en "Guardar" cuando hayas terminado de posicionar todos los puntos',
    currently_moving: 'Actualmente moviendo: {component}',
    bill_of_materials: 'Lista de Materiales ({count} componentes)',
    select_version_to_view: 'Selecciona una versión para ver los componentes',
    status: 'Estado',
    component: 'Componente',
    current_stock: 'Stock Actual',
    required: 'Necesario',
    shortage: 'Faltante',
    supplier: 'Proveedor',
    exploded_view: 'Vista Explotada',
    total_required: 'Total Requerido',
    current_stock_total: 'Stock Actual',
    total_shortage: 'Faltante Total',
    ready_to_produce: 'Listo para Producir',
    
    // Database Admin page
    database_administration: 'Administración de Base de Datos',
    inspect_analyze_raw_data: 'Inspecciona y analiza los datos RAW almacenados en las entidades',
    rate_limit_active: 'Rate Limit Activo',
    error: 'Error',
    api_rate_limited: 'La API está con límite de tasa. Por favor espera antes de hacer más solicitudes.',
    entity: 'Entidad',
    search: 'Buscar',
    search_all_fields: 'Buscar en todos los campos...',
    update: 'Actualizar',
    waiting: 'Esperando...',
    loading: 'Cargando...',
    export_json: 'Exportar JSON',
    total_records: 'Total Registros:',
    filtered: 'Filtrados:',
    total_fields: 'Campos Totales:',
    unmapped_fields: 'Campos No Mapeados:',
    unmapped_fields_found: 'Campos no mapeados encontrados en {entity}:',
    raw_data: 'Datos de {entity} ({count} registros)',
    loading_data: 'Cargando datos...',
    error_loading_data: 'Error al cargar datos',
    no_records_found: 'No se encontraron registros',
    view_json: 'Ver JSON',
    json_raw: 'JSON Raw - {entity} #{id}',
    
    // Quality Control page
    quality_control_station: 'Estación de Control de Calidad',
    test_device_quality: 'Prueba la calidad y funcionalidad de dispositivos y dinosaurios',
    select_qc_type: 'Selecciona el tipo de Control de Calidad',
    qc_by_device: 'QC por Dispositivo',
    qc_by_dinosaur: 'QC por Dinosaurio',
    qc_device_description: 'Realiza pruebas directamente a un dispositivo usando su ID único.',
    qc_dinosaur_description: 'Inicia el proceso de QC para un dinosaurio ensamblado usando su RFID.',
    back_to_selection: 'Volver a Selección',
    select_device_for_qc: 'Seleccionar Dispositivo para QC',
    select_dinosaur_for_qc: 'Seleccionar Dinosaurio para QC',
    enter_device_id: 'Ingresar ID del dispositivo...',
    scan_enter_dinosaur_rfid: 'Escanear o ingresar RFID del dinosaurio...',
    dinosaur_selected: 'Dinosaurio Seleccionado',
    rfid: 'RFID',
    device_to_test: 'Dispositivo a Probar',
    current_status: 'Estado Actual',
    assembled: 'Ensamblado',
    last_qc: 'Último QC',
    never: 'Nunca',
    start_qc_tests: 'Iniciar Tests de Quality Control',
    running_tests: 'Ejecutando Tests...',
    test_progress: 'Progreso de Tests',
    test_x_of_y: 'Test {current} de {total}',
    percent_completed: '{percent}% completado',
    action_required: '¡ACCIÓN REQUERIDA!',
    action_completed: 'Acción Completada',
    qc_results: 'QC Resultados',
    device_approved: 'DISPOSITIVO APROBADO',
    device_failed: 'DISPOSITIVO FALLIDO',
    tests_passed: '{passed} de {total} tests aprobados',
    continue_save_results: 'Continuar - Guardar Resultados',
    complete_event_log: 'Log de Eventos Completo',
    showing_all_events: 'Mostrando todos los {count} eventos registrados',
    view_details: 'Ver detalles',
    device_not_found_qc: 'Dispositivo no encontrado. Por favor verifica el ID e intenta de nuevo.',
    dinosaur_not_found_qc: 'Dinosaurio no encontrado. Por favor verifica el RFID e intenta de nuevo.',
    no_device_id_associated: 'Este dinosaurio no tiene un ID de dispositivo asociado.',
    
    // Search page
    global_search: 'Búsqueda Global',
    search_across_inventory: 'Busca en todo tu sistema de inventario',
    search_placeholder: 'Buscar por RFID, ID de dispositivo, número de orden, nombre de componente, etc...',
    search_results: 'Resultados de Búsqueda',
    no_results_found: 'No se encontraron resultados',
    try_different_search: 'Prueba con un término de búsqueda diferente',
    dinosaur_result: 'Dinosaurio',
    device_result: 'Dispositivo',
    sale_result: 'Venta',
    component_result: 'Componente',
    version_result: 'Versión',

    // User Management
    user_management: 'Gestión de Usuarios',
    user_management_title: 'Gestión de Usuarios',
    user_management_subtitle: 'Edita los detalles y permisos de acceso de los usuarios.',
    user_list: 'Lista de Usuarios',
    invite_users_notice: 'Los nuevos usuarios deben ser invitados desde los ajustes de la plataforma.',
    user: 'Usuario',
    user_code: 'Código de Usuario',
    role: 'Rol',
    permissions: 'Permisos',
    no_permissions_assigned: 'Sin permisos asignados',
    edit_user_permissions_for: 'Editar permisos para',
    description: 'Descripción',
    access_permissions: 'Permisos de Acceso',
    save_changes: 'Guardar Cambios',
    admin: 'Admin',
    access_denied: 'Acceso Denegado',
    admin_only_access: 'Esta sección está disponible solo para administradores.',
    error_updating_user: 'Error al actualizar el usuario',

    // Operator Management
    operator_management: 'Gestión de Operarios',
    operator_management_title: 'Gestión de Operarios',
    operator_management_subtitle: 'Administra códigos de operarios y permisos de acceso.',
    add_operator: 'Agregar Operario',
    operator_name: 'Nombre del Operario',
    operator_code_4_digits: 'Código de Acceso (4 dígitos)',
    operator_code_4_digits_validation: 'El código debe ser exactamente 4 dígitos numéricos',
    operator_login_prompt: 'Ingrese su código de operario',
    operator_code_invalid: 'Código de operario inválido',
    operator_login_error: 'Error al iniciar sesión',
    no_operators_found: 'No se encontraron operarios',
    add_first_operator_prompt: 'Agrega tu primer operario para comenzar.',
    edit_operator_for: 'Editar Operario: {name}',
    add_operator_desc: 'Crea un nuevo operario con código de acceso de 4 dígitos',
    edit_operator_desc: 'Modifica los datos y permisos del operario',
    operator: 'Operario',
    logout: 'Cerrar Sesión',
    code: 'Código',
    error_saving_operator: 'Error guardando operario',
    error_deleting_operator: 'Error eliminando operario',
    confirm_delete_operator: '¿Estás seguro de que quieres eliminar este operario? Esta acción no se puede deshacer.',
    // Operator Management - Additional
    administrator: 'Administrador',
    administrator_description: 'Los administradores tienen acceso completo a todas las secciones y pueden gestionar otros operarios.',
    admin_has_all_permissions: 'Los administradores tienen acceso automáticamente a todas las secciones.',
    operator_role_description_placeholder: 'Ej: Operario de línea de ensamblaje',
    admin_verification: 'Verificación de Administrador',
    enter_admin_pin_to_view: 'Ingresa el PIN de administrador para ver el código',
    admin_pin: 'PIN de Administrador',
    verify: 'Verificar',
    incorrect_admin_pin: 'PIN de administrador incorrecto',
    
    // Dinosaur Form
    edit_dinosaur: 'Editar Dinosaurio',
    slack_bot: 'Slack Bot',

    // WIP Loading System
    wip_loading: 'Carga WIP',
    wip_loading_station: 'Estación de Carga WIP',
    wip_loading_subtitle: 'Carga diaria de lotes para producción - Preparación antes del ensamblaje',
    active_wip_today: 'WIP Activo - Hoy',
    complete_wip: 'Completar WIP',
    completed: 'Completadas',
    units: 'unidades',
    loaded_by: 'Cargado por',
    batches_loaded: 'Lotes Cargados',
    available_stock: 'disp.',
    no_active_wip_warning: '⚠️ No hay WIP Loading activo para hoy. Los operarios NO podrán registrar dispositivos hasta que se complete el WIP Loading.',
    create_wip_loading_today: 'Crear WIP Loading para Hoy',
    wip_loading_description: 'Selecciona la versión y escanea los lotes que se usarán en producción',
    version_to_assemble: 'Versión a Ensamblar*',
    select_version_placeholder: 'Seleccionar versión...',
    scan_batch: 'Escanear Lote',
    scan_batch_qr_placeholder: 'Escanear código QR del lote...',
    batch_components_to_scan: 'Componentes de Tipo Lote a Escanear ({scanned}/{total})',
    all_scanned: 'Todos escaneados',
    pending: 'Pendiente',
    complete_wip_loading: 'Completar WIP Loading',
    completing_wip: 'Completando WIP...',
    no_batch_components: 'Esta versión no tiene componentes que requieran escaneo de lote. Puedes crear el WIP directamente.',
    batch_not_found: '❌ Lote "{batch}" no encontrado en el inventario',
    component_not_required: '❌ El componente "{component}" no es requerido en esta versión',
    already_scanned: '⚠️ Ya se escaneó un lote para "{component}"',
    no_stock_available: '❌ Lote "{batch}" no tiene stock disponible ({quantity} unidades)',
    batch_scanned_successfully: '✅ Lote de "{component}" escaneado correctamente',
    remove: 'Quitar',
    creating_wip: 'Creando WIP Loading...',
    please_select_version: 'Por favor, selecciona una versión',
    please_scan_all_batches: 'Por favor, escanea todos los lotes requeridos antes de completar la carga WIP',
    error_creating_wip: 'Error al crear la carga WIP:',
    error_completing_wip: 'Error al completar la carga WIP:',
    confirm_complete_wip: '¿Marcar la carga WIP de hoy como completada? Esto cerrará la sesión de producción.',
    // WIP Loading - additional translations
    quantity_to_load: 'Cantidad a Cargar',
    quantity_to_load_placeholder: 'Ingresa cantidad...',
    components_to_load: 'Componentes a Cargar',
    select_component_from_list: 'Selecciona un componente de la lista a la izquierda para comenzar a cargar',
    loading_details: 'Detalles de Carga',
    bins_loaded: 'Bins Cargados',
    no_bins_loaded_yet: 'Aún no se han cargado bins para este componente',
    // WIP Loading - bin replacement
    bin_already_exists_for_component: 'Este componente ya tiene un bin cargado',
    replace_existing_bin_warning: 'El componente "{componentName}" ya tiene el bin "{existingBin}" cargado con {quantity} unidades de la PO {poNumber}.\n\n¿Seguro que quieres reemplazarlo con el nuevo bin "{newBin}"?',
    bin_replaced_successfully: 'Bin reemplazado exitosamente',

    // SKU System
    sku_base: 'SKU Base (Nombre en Código)',
    version_number: 'Número de Versión',
    color_name_placeholder: 'Nombre del color (ej: Quartz)',
    color_code_placeholder: 'Código (ej: QU)',
    sku_preview: 'SKU Final',
    color_already_exists: 'Este color o código ya existe',

    // Shipping section
    shipping: 'Envíos',
    shipping_station: 'Estación de Envíos',
    register_shipments_tracking: 'Registra envíos y rastrea paquetes a USA',
    new_shipment: 'Nuevo Envío',
    scan_dinosaurs_add_tracking: 'Escanea dinosaurios y agrega información de rastreo',
    tracking_number: 'Número de Rastreo',
    scan_dinosaur_rfids: 'Escanear RFIDs de Dinosaurios',
    scan_or_enter_rfid: 'Escanear o ingresar RFID...',
    scanned_dinosaurs: 'Dinosaurios Escaneados',
    shipment_notes_placeholder: 'Transportista, instrucciones especiales, etc...',
    register_shipment: 'Registrar Envío',
    registering: 'Registrando',
    recent_shipments: 'Envíos Recientes',
    tracking: 'Rastreo',
    shipped_by: 'Enviado por',
    date: 'Fecha',
    dinosaurs_in_shipment: 'Dinosaurios en este Envío',
    no_shipments_registered: 'No hay envíos registrados',
    start_by_registering_first_shipment: 'Comienza registrando tu primer envío',
    tracking_number_required: 'El número de rastreo es requerido',
    at_least_one_rfid_required: 'Se requiere al menos un RFID de dinosaurio',
    shipment_registered_successfully: '¡Envío registrado exitosamente!',
    error_registering_shipment: 'Error registrando envío',
    confirm_delete_shipment: '¿Estás seguro de que quieres eliminar el envío {tracking}?',
    error_deleting_shipment: 'Error eliminando envío',
    rfid_already_scanned: 'Este RFID ya ha sido escaneado',
    dinosaur_not_found_rfid: 'Dinosaurio con RFID {rfid} no encontrado',
    dinosaur_not_sold_warning: 'Advertencia: El dinosaurio {rfid} tiene estado "{status}" (no vendido)',
    rfid_scanned_successfully: 'RFID {rfid} escaneado exitosamente',
    error_verifying_dinosaur: 'Error verificando dinosaurio',

    // Christmas Countdown
    countdown_to_christmas: 'Cuenta Regresiva para Navidad',
    time_until_christmas: 'Tiempo hasta el Día de Navidad',
    days: 'Días',
    hours: 'Horas',
    minutes: 'Minutos',
    seconds: 'Segundos',
    merry_christmas: '🎄 ¡Feliz Navidad! 🎄',
    its_christmas: '¡Es Navidad!',
    merry_christmas_message: '¡Te deseamos una maravillosa Navidad llena de alegría y felicidad!',
    christmas_message_far: '🎅 ¡Santa está preparando su trineo!',
    christmas_message_soon: '🎁 ¡La Navidad se acerca! ¡Hora de ser festivos!',
    christmas_message_very_soon: '⛄ ¡Ya casi! ¡La magia de la Navidad está en el aire!',

    // QuickQC translations
    quick_qc_station: 'Estación Quick QC',
    quick_qc_subtitle: 'Test rápido de control de calidad ESP32',
    ensure_device_on_range: 'Asegúrate de que el dispositivo ESP32 esté encendido y dentro del rango',
    searching_device: 'Buscando dispositivo...',
    start_qc_test: 'Iniciar Test QC',
    running_tests: 'Ejecutando Tests',
    test_audio: 'Test de Audio',
    test_mic_basic: 'Test Mic Básico',
    test_mic_lr_balance: 'Test Mic L/R Balance',
    test_battery: 'Test de Batería',
    adjust_volume: 'Ajuste de Volumen',
    event_log: 'Log de Eventos',
    test_another_device: 'Probar Otro Dispositivo',

    // New additions for WIPLoading date error
    unknown_date: 'Fecha desconocida',
    invalid_date: 'Fecha inválida',

    // Purchase Order Form translations
    supplier_name: 'Proveedor',
    supplier_name_placeholder: 'Nombre del proveedor...',
    invoice_number: 'Número de Factura',
    invoice_number_placeholder: 'INV-2024-001...',
    tracking_number_po: 'Número de Seguimiento', // Renamed to avoid collision with sales/shipping
    tracking_number_placeholder: '1Z999AA1234567890...',
    estimated_delivery: 'Entrega estimada',
    items_to_order: 'Artículos a Solicitar',
    component_po: 'Componente', // Renamed to avoid collision with general 'component'
    select_component_po: 'Seleccionar componente', // Renamed to avoid collision
    quantity_po: 'Cantidad', // Renamed to avoid collision
    additional_notes_po: 'Notas Adicionales', // Renamed to avoid collision
    additional_notes_placeholder_po: 'Instrucciones especiales, comentarios...', // Renamed to avoid collision
    intelligent_document_processing: 'Procesamiento Inteligente de Documentos',
    upload_po_photo_description: 'Sube una foto de tu orden de compra y la IA extraerá automáticamente toda la información.',
    upload_po_photo: 'Subir Foto de Orden de Compra',
    processing: 'Procesando...',
    creating: 'Creando...',
    saving: 'Guardando...',
    save_changes: 'Guardar Cambios',
    create_purchase_order: 'Crear Orden de Compra',
    edit_purchase_order: 'Editar Orden de Compra',
    document_processed_successfully: '¡Documento procesado exitosamente! Revisa la información extraída y ajusta si es necesario.',
    error_processing_document: 'Error al procesar el documento. Por favor intenta de nuevo o ingresa los datos manualmente.',
    // Purchase Order Form - Price fields
    unit_price: 'Precio Unitario',
    total_price: 'Precio Total',
    unit_price_placeholder: 'Precio por unidad...',
    total_price_placeholder: 'Precio total...',
    price_required: 'El precio es obligatorio',
    subtotal: 'Subtotal',
    grand_total: 'Total General',
    batch_info: 'Info del Batch',
    batch_info_placeholder: 'Número de lote del proveedor, fecha de producción, códigos internos...',
    batch_info_description: 'Información interna del proveedor sobre este lote (opcional)',
    
    // Bin Number (replacing Batch)
    bin_number: 'Número de Bin',
    scan_bin_number: 'Escanear Número de Bin',
    bin_number_placeholder: 'Escanear número de bin...',
    select_purchase_order: 'Seleccionar Orden de Compra',
    link_bin_to_po: 'Vincular Bin a OC',
    bin_linked_successfully: 'Bin vinculado correctamente',
    bin_already_loaded: 'Este bin ya está cargado',
    no_matching_pos: 'No se encontraron órdenes de compra con este componente',
    quantity_in_po: 'Cant. en OC',
    already_received: 'Ya Recibido',
    available_in_po: 'Disponible',
    select_po_with_component: 'Selecciona una OC que contenga este componente',
    bins_to_load: 'Bins a Cargar',
    bin_info: 'Info del Bin',
    linked_to_po: 'Vinculado a OC',

    scan_or_select_po: 'Escanear o Seleccionar OC',
    scan_po_number: 'Escanear Número de OC',
    scan_po_placeholder: 'Escanear número de OC...',
    or_select_from_list: 'O selecciona de las OC disponibles:',
    no_pos_with_component: 'No hay órdenes de compra con este componente',

    scan: 'Escanear',
    and: 'y',
    more_items: 'artículos más',
    total: 'Total',
    no_location: 'Sin ubicación',
    select_warehouse: 'Seleccionar warehouse',
    active_warehouse: 'Warehouse Activo',
    no_warehouses_configured: 'No hay warehouses configurados',
    create_warehouse: 'Crear warehouse',
    warehouse: 'Warehouse',
  },
  zh: {
    // Navigation and layout
    dashboard: '仪表板',
    components: '组件',
    dinosaurs: '恐龙',
    devices: '设备',
    sales: '销售',
    search: '搜索',
    bom_management: 'BOM管理',
    inventory_management: '库存管理',
    odoo_sync: 'Odoo同步',
    versions: '版本',
    quality_control: '质量控制',
    db_admin: '数据库管理',
    management: '管理',
    quick_stats: '快速统计',
    inventory_manager: '库存管理员',
    
    // Dashboard
    dashboard_title: 'DinoTrack仪表板',
    dashboard_subtitle: '您的恐龙库存控制面板',
    total_components: '总组件数',
    total_dinosaurs: '总恐龙数',
    total_sales: '总销售数',
    available_dinos: '可用恐龙',
    low_stock: '库存不足',
    sales_this_week: '本周销售',
    recent_dinosaurs: '最新恐龙',
    critical_components: '关键组件',
    all_components_sufficient_stock: '所有组件库存充足',
    no_dinosaurs_registered: '没有已注册的恐龙',
    
    // Components page
    component_management: '组件管理',
    manage_parts_components_inventory: '管理您的零件和组件库存',
    add_component: '添加组件',
    search_components_placeholder: '按名称、批次或序列号搜索组件...',
    category: '类别',
    tracking: '跟踪',
    all: '全部',
    by_batch: '按批次',
    by_unit: '按单位',
    chips: '芯片',
    batteries: '电池',
    sensors: '传感器',
    motors: '电机',
    structures: '结构',
    others: '其他',
    no_components_registered: '没有已注册的组件',
    start_adding_first_component: '开始向库存添加您的第一个组件',
    confirm_delete_component: '确定要删除组件"{componentName}"吗？此操作无法撤销。',
    
    // Dinosaurs page
    dinosaur_registration_station: '恐龙注册站',
    register_dinosaurs_step_by_step: '使用分步指导助手注册恐龙。',
    assembly_station: '组装站',
    registration_assistant: '注册助手',
    select_dinosaur_version_step: '1. 选择恐龙版本',
    select_color_step: '2. 选择颜色',
    scan_plush_rfid_step: '3. 扫描毛绒RFID',
    scan_device_id_step: '4. 扫描设备ID',
    additional_notes_step: '5. 附加备注（可选）',
    confirm_register_step: '6. 确认并注册',
    choose_version: '选择版本...',
    select_color: '选择颜色...',
    waiting_rfid_scan: '等待RFID扫描...',
    device_id_placeholder: '设备ID...',
    special_observations_placeholder: '特殊观察、修改等...',
    continue: '继续',
    back: '返回',
    register_dinosaur: '注册恐龙',
    version: '版本',
    color: '颜色',
    device_id: '设备ID',
    step_x_of_y: '步骤 {current} / {total}',
    search_rfid_device_placeholder: '按RFID或设备ID搜索...',
    total_dinosaurs: '总计：{count} 只恐龙',
    all_statuses: '所有状态',
    all_colors: '所有颜色',
    all_versions: '所有版本',
    available: '可用',
    sold: '已售出',
    maintenance: '维护中',
    damaged: '损坏',
    unverified: '未验证',
    pink: '粉色',
    teal: '青色',
    lavender: '淡紫色',
    green: '绿色',
    interference_detected_rfids: '检测到干扰！多个RFID标签太近。请分开它们并重新扫描。',
    missing_data_restart_process: '缺少必需数据。请重新启动注册过程。',
    device_not_found_warning: '未找到ID为"{deviceId}"的就绪状态设备。是否仍要注册？',
    error_registering_dinosaur: '注册恐龙时出错。请重试。',
    force_register_warning_note: '警告：强制注册。设备 {deviceId} 未找到就绪状态。',
    error_force_register: '强制注册时出错。请重试。',
    cannot_delete_sold_dinosaur: '无法删除已售出的恐龙。',
    confirm_delete_dinosaur: '确定要删除RFID为 {rfid_code} 的恐龙吗？此操作无法撤销。',
    dinosaur_registered_successfully_rfid: '恐龙注册成功！RFID：',
    device: '设备',
    assembled_by: '组装者',
    device_defective_warning: '设备 {deviceId} 被标记为有缺陷。是否仍要注册？',
    qc_failed_warning: '设备 {deviceId} 未通过QC测试：{failedTests}。是否仍要注册？',
    qc_not_tested_warning: '设备 {deviceId} 尚未进行QC测试。是否仍要注册？',
    device_not_ready_warning: '设备 {deviceId} 处于"{status}"状态，未就绪。是否仍要注册？',
    force_register_note_defective: '警告：强制注册。设备 {deviceId} 被标记为有缺陷。',
    force_register_note_qc_failed: '警告：强制注册。设备 {deviceId} 未通过QC测试：{failedTests}。',
    force_register_note_qc_not_tested: '警告：强制注册。设备 {deviceId} 尚未进行QC测试。',
    force_register_note_not_ready: '警告：强制注册。设备 {deviceId} 处于非就绪状态。',
    force_register_note_device_not_found: '警告：强制注册。设备 {deviceId} 未在库存中找到。',
    continue_anyway: '仍然继续',
    cancel_and_review: '取消并审查',
    
    // Dinosaur Versions page
    dinosaur_versions: '恐龙版本',
    create_manage_configurations: '创建和管理恐龙配置和配方',
    create_version: '创建版本',
    edit_version: '编辑版本',
    create_new_version: '创建新版本',
    model_name: '型号名称',
    available_colors: '可用颜色',
    write_color_placeholder: '写颜色（例如，粉色）',
    components_configuration: '组件配置',
    option_1_scan_batch: '选项1：扫描组件的批次或序列号条形码以添加它。',
    scan_batch_serial_placeholder: '扫描批次或序列号...',
    option_2_select_manually: '选项2：手动选择组件。',
    select_component: '选择组件',
    select_batch: '选择批次',
    add: '添加',
    added_components: '已添加的组件 ({count})',
    batch: '批次',
    individual: '单个',
    version_notes: '版本备注',
    version_notes_placeholder: '特殊功能、组装备注、版本更改等...',
    cancel: '取消',
    saving: '保存中...',
    saved: '已保存',
    save_error: '保存错误',
    no_versions_created: '未创建版本',
    create_first_version: '创建您的第一个恐龙版本以开始管理配置。',
    duplicate: '复制',
    edit: '编辑',
    delete: '删除',
    hide_details: '隐藏详情',
    show_details: '显示详情',
    components_count: '组件 ({count})',
    notes: '备注',
    no_components_configured: '此版本未配置组件。',
    no_notes_version: '此版本没有备注。',
    units_made: '已制造单位 ({count})',
    no_dinosaurs_registered_version: '尚未使用此版本注册恐龙。',
    create_editable_copy: '创建此版本的新可编辑副本',
    cannot_delete_version_has_dinosaurs: '无法删除已注册恐龙的版本。',
    // Additional Dinosaur Versions translations
    cannot_delete_version_has_dinosaurs_with_count: '无法删除此版本，因为它已注册了 {count} 只恐龙。请先删除恐龙。',
    confirm_delete_version: '确定要删除版本"{name}"吗？此操作无法撤销。',
    enter_duplicate_version_name: '输入重复版本的名称：',
    copy: '副本',
    enter_different_name_duplicate: '请为重复版本输入不同的名称。',
    duplicated_from: 'Duplicated from',
    version_duplicated_successfully: '版本"{newName}"已成功创建为"{originalName}"的副本。',
    error_duplicating_version: '创建重复版本时出错。请重试。',
    component_already_added: '组件"{name}"已添加到此版本。',
    select_components_for_version: '选择此版本所需的组件（具体批次将在 WIP Loading 中选择）',
    no_tracking: '无跟踪',
    batches_selected_in_wip: '具体批次在 WIP Loading 中选择',
    created_on: '创建于',
    
    // Devices page
    device_registration_station: '设备注册站',
    register_devices_step_by_step: '使用分步指导注册新设备。',
    device_registration_assistant: '设备注册助手',
    select_dinosaur_version: '1. 选择恐龙版本',
    scan_device_id: '2. 扫描或输入设备ID',
    scan_serial_numbers: '3. 扫描序列号',
    additional_notes_optional_device: '4. 附加备注（可选）',
    confirm_and_register: '5. 确认并注册',
    register_device: '注册设备',
    scan_or_enter_device_id: '扫描或输入设备ID...',
    scan_serial_number: '扫描序列号...',
    no_serial_components_required: '3. 不需要序列号组件',
    this_version_no_serials: '此版本不需要扫描序列号。',
    continue_to_notes: '继续到备注',
    device_registered_successfully: '设备注册成功：ID',
    showing_x_of_y_devices: '显示 {filtered} / {total} 个设备',
    ready: '就绪',
    used: '已使用',
    defective: '有缺陷',
    search_by_id_notes_serials: '按ID、备注或序列号搜索...',
    no_devices_found: '未找到设备',
    devices_will_appear: '注册第一个设备后，设备将显示在这里',
    
    // Sales page
    sales_registration_station: '销售注册站',
    editing_sale: '编辑销售',
    modify_sale_details_prompt: '修改此销售的详细信息。',
    register_sales_quickly: '通过扫描每只恐龙的RFID快速注册销售。',
    order_number: '订单号',
    scan_dinosaur_rfid: '扫描恐龙RFID',
    rfid_detected: '检测到RFID',
    waiting_for_scan_placeholder: '等待RFID扫描...',
    scanning_in_progress: '扫描中... {current}/{total} 字符',
    confirmed_rfid_label: '已确认的RFID：',
    additional_notes_optional: '附加备注（可选）',
    sale_comments_placeholder: '关于销售的评论、特殊要求等。',
    rfid_issue_title: '检测到RFID问题',
    continue_anyway_button: '仍然继续',
    cancel_button: '取消',
    register_sale_button: '注册销售',
    update_sale_button: '更新销售',
    cancel_edit_button: '取消编辑',
    sale_updated_success: '销售已更新：',
    sale_registered_success: '销售已注册：',
    sale_deleted_success: '销售已删除：',
    with_rfid_label: '使用RFID',
    recent_sales_title: '最近的销售',
    no_recent_sales_message: '没有最近的销售可显示。',
    scan_rfid_required: '请扫描有效的RFID代码以注册销售。',
    order_number_required: '订单号是必需的。',
    interference_detected: '检测到干扰！多个RFID标签太近。请分开它们并重新扫描。',
    rfid_too_long: '无效扫描。RFID代码太长（{length} 字符，预期 {expected}）。',
    dino_not_found_with_history: '库存中未找到RFID为 {rfid} 的恐龙。但是，它之前在 {formattedSaleDate}（{timeAgo}）的订单 {orderNumber} 中售出。此RFID已注册 {count} 笔销售。',
    dino_not_found_no_history: '库存中未找到RFID为 {rfid} 的恐龙，也未找到以前的销售记录。',
    dino_already_sold: '这只恐龙已经在 {formattedSaleDate}（{timeAgo}）的订单 {orderNumber} 中售出。此RFID已注册 {count} 笔销售。',
    dino_not_available: 'RFID为 {rfid} 的恐龙不可用（当前状态：{status}）。',
    multiple_available_dinos_warning: '警告：找到多个RFID为 {rfid} 的可用恐龙',
    
    // Inventory Management
    inventory_management_hub: '库存管理中心',
    central_hub_for_inventory: '您的采购订单、收货和库存控制中心。',
    purchase_orders: '采购订单',
    receiving: '收货',
    stock_control: '库存控制',
    production_plan: '生产计划',
    
    // PO Sub-page
    create_and_manage_pos: '创建和管理您的组件采购订单。',
    create_po: '创建采购订单',
    no_pos_found: '未找到采购订单',
    create_first_po: '创建您的第一个采购订单以开始。',
    ordered_on: '订购于',
    pending: '待处理',
    in_transit: '运输中',
    partially_received: '部分收到',
    completed: '已完成',
    cancelled: '已取消',
    
    // Receiving Sub-page
    receive_items_against_po: '根据未结采购订单接收物料以更新您的库存。',
    select_po_to_receive: '选择要接收的采购订单',
    no_open_pos: '没有未结采购订单',
    create_po_to_receive: '首先创建采购订单以开始接收物品',
    progress: '进度',
    items: '项目',
    receiving_items_for: '接收物品',
    select_po_to_start_receiving: '选择采购订单开始',
    click_on_po_card_above: '点击上面的采购订单卡片查看其物品并开始接收',
    
    // Stock Control Sub-page
    view_current_inventory_levels: '查看所有组件的当前库存水平。',
    
    // Production Plan Sub-page
    plan_dinosaur_production: '根据可用组件库存计划您的恐龙生产。',

    // BOM Management page
    bom_interactive_viewer: 'BOM交互式查看器',
    interactive_bom_view: '物料清单交互式视图',
    debug_mode: '调试模式',
    exit_debug: '退出调试',
    save: '保存',
    reset: '重置',
    dinosaur_version: '恐龙版本',
    select_version: '选择版本',
    production_target: '生产目标',
    production_quantity_placeholder: '生产数量...',
    debug_mode_activated: '调试模式已激活',
    drag_points: '拖动图像上的点以重新定位它们',
    save_when_finished: '完成所有点的定位后单击"保存"',
    currently_moving: '当前移动：{component}',
    bill_of_materials: '物料清单（{count} 个组件）',
    select_version_to_view: '选择版本以查看组件',
    status: '状态',
    component: '组件',
    current_stock: '当前库存',
    required: '需要',
    shortage: '短缺',
    supplier: '供应商',
    exploded_view: '分解视图',
    total_required: '总需求',
    current_stock_total: '当前库存',
    total_shortage: '总短缺',
    ready_to_produce: '准备生产',
    
    // Database Admin page
    database_administration: '数据库管理',
    inspect_analyze_raw_data: '检查和分析实体中存储的原始数据',
    rate_limit_active: '速率限制激活',
    error: '错误',
    api_rate_limited: 'API受速率限制。请稍等再发出更多请求。',
    entity: '实体',
    search: '搜索',
    search_all_fields: '在所有字段中搜索...',
    update: '更新',
    waiting: '等待中...',
    loading: '加载中...',
    export_json: '导出JSON',
    total_records: '总记录数：',
    filtered: '已筛选：',
    total_fields: '总字段数：',
    unmapped_fields: '未映射字段：',
    unmapped_fields_found: '在 {entity} 中找到未映射字段：',
    raw_data: '来自 {entity} 的数据（{count} 条记录）',
    loading_data: '加载数据中...',
    error_loading_data: '加载数据时出错',
    no_records_found: '未找到记录',
    view_json: '查看JSON',
    json_raw: 'JSON原始 - {entity} #{id}',
    
    // Quality Control page
    quality_control_station: '质量控制站',
    test_device_quality: '测试设备和恐龙的质量和功能',
    select_qc_type: '选择质量控制类型',
    qc_by_device: '按设备QC',
    qc_by_dinosaur: '按恐龙QC',
    qc_device_description: '使用唯一ID直接对设备进行测试。',
    qc_dinosaur_description: '使用RFID对组装好的恐龙启动QC流程。',
    back_to_selection: '返回选择',
    select_device_for_qc: '选择设备进行QC',
    select_dinosaur_for_qc: '选择恐龙进行QC',
    enter_device_id: '输入设备ID...',
    scan_enter_dinosaur_rfid: '扫描或输入恐龙RFID...',
    dinosaur_selected: '已选择的恐龙',
    rfid: 'RFID',
    device_to_test: '待测试设备',
    current_status: '当前状态',
    assembled: '已组装',
    last_qc: '上次QC',
    never: '从未',
    start_qc_tests: '开始质量控制测试',
    running_tests: '正在运行测试...',
    test_progress: '测试进度',
    test_x_of_y: '测试 {current} / {total}',
    percent_completed: '{percent}% 已完成',
    action_required: '需要操作！',
    action_completed: '操作完成',
    qc_results: 'QC结果',
    device_approved: '设备通过',
    device_failed: '设备失败',
    tests_passed: '{passed} / {total} 项测试通过',
    continue_save_results: '继续 - 保存结果',
    complete_event_log: '完整事件日志',
    showing_all_events: '显示所有 {count} 条记录的事件',
    view_details: '查看详情',
    device_not_found_qc: '未找到设备。请检查ID并重试。',
    dinosaur_not_found_qc: '未找到恐龙。请检查RFID并重试。',
    no_device_id_associated: '此恐龙没有关联的设备ID。',
    
    // Search page
    global_search: '全局搜索',
    search_across_inventory: '在整个库存系统中搜索',
    search_placeholder: '按RFID、设备ID、订单号、组件名称等搜索...',
    search_results: '搜索结果',
    no_results_found: '未找到结果',
    try_different_search: '尝试不同的搜索词',
    dinosaur_result: '恐龙',
    device_result: '设备',
    sale_result: '销售',
    component_result: '组件',
    version_result: '版本',

    // User Management
    user_management: '用户管理',
    user_management_title: '用户管理',
    user_management_subtitle: '编辑用户详细信息和访问权限。',
    user_list: '用户列表',
    invite_users_notice: '新用户必须通过平台设置进行邀请。',
    user: '用户',
    user_code: '用户代码',
    role: '角色',
    permissions: '权限',
    no_permissions_assigned: '未分配权限',
    edit_user_permissions_for: '编辑权限于',
    description: '描述',
    access_permissions: '访问权限',
    save_changes: '保存更改',
    admin: '管理员',
    access_denied: '访问被拒绝',
    admin_only_access: '此部分仅供管理员使用。',
    error_updating_user: '更新用户时出错',

    // Operator Management
    operator_management: '操作员管理',
    operator_management_title: '操作员管理',
    operator_management_subtitle: '管理操作员代码和访问权限。',
    add_operator: '添加操作员',
    operator_name: '操作员姓名',
    operator_code_4_digits: '访问代码（4位数字）',
    operator_code_4_digits_validation: '代码必须是4位数字',
    operator_login_prompt: '输入您的操作员代码',
    operator_code_invalid: '无效的操作员代码',
    operator_login_error: '登录错误',
    no_operators_found: '未找到操作员',
    add_first_operator_prompt: '添加您的第一个操作员开始使用。',
    edit_operator_for: '编辑操作员：{name}',
    add_operator_desc: '创建一个带有4位访问代码的新操作员',
    edit_operator_desc: '修改操作员数据和权限',
    operator: '操作员',
    logout: '注销',
    code: '代码',
    error_saving_operator: '保存操作员时出错',
    error_deleting_operator: '删除操作员时出错',
    confirm_delete_operator: '您确定要删除此操作员吗？此操作无法撤销。',
    // Operator Management - Additional
    administrator: 'Administrador',
    administrator_description: 'Los administradores tienen acceso completo a todas las secciones y pueden gestionar otros operarios.',
    admin_has_all_permissions: 'Los administradores tienen acceso automáticamente a todas las secciones.',
    operator_role_description_placeholder: 'Ej: Operario de línea de ensamblaje',
    admin_verification: 'Verificación de Administrador',
    enter_admin_pin_to_view: 'Ingresa el PIN de administrador para ver el código',
    admin_pin: 'PIN de Administrador',
    incorrect_admin_pin: 'PIN de administrador incorrecto',
    verify: 'Verificar',

    // Dinosaur Form
    edit_dinosaur: '编辑 Dinosaurio',
    slack_bot: 'Slack Bot',

    // WIP Loading System
    wip_loading: 'WIP装载',
    wip_loading_station: 'WIP装载站',
    wip_loading_subtitle: '日常批次装载以进行生产 - 组装前的准备',
    active_wip_today: '活跃的WIP - 今天',
    complete_wip: '完成WIP',
    completed: '已完成',
    units: '单位',
    loaded_by: '装载者',
    batches_loaded: '已装载批次',
    available_stock: '可用',
    no_active_wip_warning: '⚠️ 今天没有活跃的WIP装载。在完成WIP装载之前，操作员将无法注册设备。',
    create_wip_loading_today: '为今天创建WIP装载',
    wip_loading_description: '选择版本并扫描将在生产中使用的批次',
    version_to_assemble: '要组装的版本*',
    select_version_placeholder: '选择版本...',
    scan_batch: '扫描批次',
    scan_batch_qr_placeholder: '扫描批次二维码...',
    batch_components_to_scan: '要扫描的批次组件（{scanned}/{total}）',
    all_scanned: '全部已扫描',
    pending: '待处理',
    complete_wip_loading: '完成WIP装载',
    completing_wip: '完成WIP中...',
    no_batch_components: '此版本没有需要批次扫描的组件。您可以直接创建WIP。',
    batch_not_found: '❌ 批次"{batch}"在库存中未找到',
    component_not_required: '❌ 组件"{component}"在此版本中不需要',
    already_scanned: '⚠️ 已经为"{component}"扫描了一个批次',
    no_stock_available: '❌ 批次"{batch}"没有可用库存（{quantity} 单位）',
    batch_scanned_successfully: '✅ "{component}"的批次扫描成功',
    remove: '移除',
    creating_wip: '创建WIP装载中...',
    // Additional WIP Loading translations
    please_select_version: '请选择版本',
    please_scan_all_batches: '完成 WIP Loading 前请扫描所有必需的批次',
    error_creating_wip: '创建 WIP Loading 时出错：',
    error_completing_wip: '完成 WIP 时出错：',
    confirm_complete_wip: '将今天的 WIP Loading 标记为已完成？这将关闭生产会话。',
    quantity_to_load: '要加载的数量',
    quantity_to_load_placeholder: '输入数量...',
    components_to_load: '要加载的组件',
    select_component_from_list: '从左侧列表中选择一个组件以开始加载',
    loading_details: '加载详情',
    bins_loaded: '已加载的货位',
    no_bins_loaded_yet: '此组件尚未加载任何货位',
    // WIP Loading - bin replacement
    bin_already_exists_for_component: '此组件已加载了一个货位',
    replace_existing_bin_warning: '组件"{componentName}"已加载货位"{existingBin}"，来自采购订单{poNumber}，数量为{quantity}个单位。\n\n您确定要用新货位"{newBin}"替换它吗？',
    bin_replaced_successfully: '货位替换成功',

    // SKU System
    sku_base: 'SKU基础（代码名称）',
    version_number: '版本号',
    color_name_placeholder: '颜色名称（例如：Quartz）',
    color_code_placeholder: '代码（例如：QU）',
    sku_preview: '最终SKU',
    color_already_exists: '此颜色或代码已存在',

    // Shipping section
    shipping: '发货',
    shipping_station: '发货站',
    register_shipments_tracking: '注册发货并追踪到美国的包裹',
    new_shipment: '新发货',
    scan_dinosaurs_add_tracking: '扫描恐龙并添加追踪信息',
    tracking_number: '追踪号码',
    scan_dinosaur_rfids: '扫描恐龙RFID',
    scan_or_enter_rfid: '扫描或输入RFID...',
    scanned_dinosaurs: '已扫描的恐龙',
    shipment_notes_placeholder: '承运商、特殊说明等...',
    register_shipment: '注册发货',
    registering: '注册中',
    recent_shipments: '最近的发货',
    tracking: '追踪',
    shipped_by: '发货人',
    date: '日期',
    dinosaurs_in_shipment: '此发货中的恐龙',
    no_shipments_registered: '没有已注册的发货',
    start_by_registering_first_shipment: '从注册您的第一批发货开始',
    tracking_number_required: '追踪号码是必需的',
    at_least_one_rfid_required: '至少需要一个恐龙RFID',
    shipment_registered_successfully: '发货注册成功！',
    error_registering_shipment: '注册发货时出错',
    confirm_delete_shipment: '您确定要删除发货 {tracking} 吗？',
    error_deleting_shipment: '删除发货时出错',
    rfid_already_scanned: '此RFID已被扫描',
    dinosaur_not_found_rfid: '未找到RFID为 {rfid} 的恐龙',
    dinosaur_not_sold_warning: '警告：恐龙 {rfid} 的状态为"{status}"（未售出）',
    rfid_scanned_successfully: 'RFID {rfid} 扫描成功',
    error_verifying_dinosaur: '验证恐龙时出错',

    // Christmas Countdown
    countdown_to_christmas: '圣诞节倒计时',
    time_until_christmas: '距离圣诞节',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒',
    merry_christmas: '🎄 圣诞快乐！🎄',
    its_christmas: '圣诞节到了！',
    merry_christmas_message: '祝您度过一个充满欢乐和幸福的美好圣诞节！',
    christmas_message_far: '🎅 圣诞老人正在准备他的雪橇！',
    christmas_message_soon: '🎁 圣诞节即将来临！该庆祝了！',
    christmas_message_very_soon: '⛄ 快到了！圣诞节的魔力弥漫在空气中！',

    // QuickQC translations
    quick_qc_station: '快速QC站',
    quick_qc_subtitle: 'ESP32快速质量控制测试',
    ensure_device_on_range: '确保ESP32设备已开启并在范围内',
    searching_device: '搜索设备中...',
    start_qc_test: '开始QC测试',
    running_tests: '正在运行测试',
    test_audio: '音频测试',
    test_mic_basic: '基本麦克风测试',
    test_mic_lr_balance: '左右平衡麦克风测试',
    test_battery: '电池测试',
    adjust_volume: '音量调整',
    event_log: '事件日志',
    test_another_device: '测试另一台设备',

    // New additions for WIPLoading date error
    unknown_date: '未知日期',
    invalid_date: '无效日期',

    // Purchase Order Form translations
    supplier_name: '供应商',
    supplier_name_placeholder: '供应商名称...',
    invoice_number: '发票号码',
    invoice_number_placeholder: 'INV-2024-001...',
    tracking_number_po: '追踪号码', // Renamed to avoid collision with sales/shipping
    tracking_number_placeholder: '1Z999AA1234567890...',
    estimated_delivery: '预计交付',
    items_to_order: '订购物品',
    component_po: '组件', // Renamed to avoid collision with general 'component'
    select_component_po: '选择组件', // Renamed to avoid collision
    quantity_po: '数量', // Renamed to avoid collision
    additional_notes_po: '附加备注', // Renamed to avoid collision
    additional_notes_placeholder_po: '特殊说明、评论...', // Renamed to avoid collision
    intelligent_document_processing: '智能文档处理',
    upload_po_photo_description: '上传您的采购订单照片，AI将自动提取所有信息。',
    upload_po_photo: '上传采购订单照片',
    processing: '处理中...',
    creating: '创建中...',
    saving: '保存中...',
    save_changes: '保存更改',
    create_purchase_order: '创建采购订单',
    edit_purchase_order: '编辑采购订单',
    document_processed_successfully: '文档处理成功！请检查提取的信息并根据需要进行调整。',
    error_processing_document: '处理文档时出错。请重试或手动输入数据。',
    // Purchase Order Form - Price fields
    unit_price: '单价',
    total_price: '总价',
    unit_price_placeholder: '单价...',
    total_price_placeholder: '总价...',
    price_required: '价格为必填项',
    subtotal: '小计',
    grand_total: '总计',
    batch_info: '批次信息',
    batch_info_placeholder: '供应商批次号、生产日期、内部代码...',
    batch_info_description: '供应商关于此批次的内部信息（可选）',
    
    // Bin Number (replacing Batch)
    bin_number: '货位号',
    scan_bin_number: '扫描货位号',
    bin_number_placeholder: '扫描货位号...',
    select_purchase_order: '选择采购订单',
    link_bin_to_po: '将货位链接到采购订单',
    bin_linked_successfully: '货位链接成功',
    bin_already_loaded: '此货位已加载',
    no_matching_pos: '未找到包含此组件的采购订单',
    quantity_in_po: '采购订单数量',
    already_received: '已接收',
    available_in_po: '可用',
    select_po_with_component: '选择包含此组件的采购订单',
    bins_to_load: '要加载的货位',
    bin_info: '货位信息',
    linked_to_po: '已链接到采购订单',

    scan_or_select_po: '扫描或选择采购订单',
    scan_po_number: '扫描采购订单号',
    scan_po_placeholder: '扫描采购订单号...',
    or_select_from_list: '或从可用的采购订单中选择:',
    no_pos_with_component: '没有包含此组件的采购订单',

    scan: '扫描',
    and: '和',
    more_items: '更多项目',
    total: '总计',
    no_location: '无位置',
    select_warehouse: '选择仓库',
    active_warehouse: '活动仓库',
    no_warehouses_configured: '未配置仓库',
    create_warehouse: '创建仓库',
    warehouse: '仓库',
  }
};

// t function with parameter support
const t = (key, params = {}) => {
  const translation = translations[getCurrentLanguage()][key] || key;
  
  // Replace parameters in the translation
  return Object.keys(params).reduce((result, param) => {
    return result.replace(`{${param}}`, params[param]);
  }, translation);
};

let currentLanguage = 'es'; // Default to Spanish

const getCurrentLanguage = () => currentLanguage;

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('dinotrack-language') || 'es';
  });

  const setLanguage = (newLanguage) => {
    setLanguageState(newLanguage);
    currentLanguage = newLanguage;
    localStorage.setItem('dinotrack-language', newLanguage);
  };

  useEffect(() => {
    currentLanguage = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
